# Generated by Django 4.0.2 on 2022-10-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_profile_cover_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('Profile_Picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('Notifications', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Commented_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Flagged_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Liked_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Reshared_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User_Followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User_Following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Author_Profile',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='post',
            name='Author_Driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
    ]
