# Generated by Django 4.0.2 on 2022-10-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_driver_remove_profile_commented_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_obj',
            name='user',
        ),
        migrations.RemoveField(
            model_name='follow_obj',
            name='user_follower',
        ),
        migrations.RemoveField(
            model_name='mute_obj',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mute_obj',
            name='user_blocker',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Block_obj',
        ),
        migrations.DeleteModel(
            name='Follow_obj',
        ),
        migrations.DeleteModel(
            name='Mute_obj',
        ),
    ]
