# Generated by Django 4.1.2 on 2022-10-28 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_driver_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='CommentCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='LikeCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='RepostAuthor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Reposted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ReshareCount',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(default=uuid.uuid1, max_length=300)),
                ('Business_Profile_Picture', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.CharField(default=uuid.uuid1, max_length=300)),
                ('Load_Weight', models.PositiveIntegerField(default=0)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Pickup_Address', models.CharField(default=uuid.uuid1, max_length=300)),
                ('Destination_Address', models.CharField(default=uuid.uuid1, max_length=300)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=75)),
                ('Business_Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
