# Generated by Django 4.1.2 on 2022-10-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_post_commentcount_remove_post_likecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='InProgress',
            field=models.BooleanField(default=False),
        ),
    ]
