# Generated by Django 4.1.2 on 2022-10-29 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_job_complete_job_inprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ImageString',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='Business_Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
