# Generated by Django 4.1.2 on 2022-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_business_profile_job_assigned_lugger'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Latitude',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Longitude',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
