# Generated by Django 4.1.2 on 2022-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_latitude_job_latitude_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Distance',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
