# Generated by Django 4.1.2 on 2022-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_job_assigned_lugger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='Pieces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
