# Generated by Django 4.1.2 on 2022-11-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_vehicle_type_job_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Size_Of_Vehicle_Needed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='main.vehicle_type'),
        ),
    ]
