# Generated by Django 4.1.2 on 2022-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_job_size_of_vehicle_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Date_Needed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
