# Generated by Django 4.1.2 on 2022-11-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Account_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.account_type'),
        ),
    ]
