# Generated by Django 4.0.2 on 2022-10-08 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_remove_follow_obj_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Author_Driver',
            new_name='Author_Profile',
        ),
    ]
