# Generated by Django 4.1.2 on 2022-10-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_job_imagestring_alter_job_business_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Business_Profile',
            new_name='Assigned_Lugger',
        ),
    ]
