# Generated by Django 4.1.2 on 2022-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Latitude',
            new_name='Latitude_Destination',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Longitude',
            new_name='Latitude_Pickup',
        ),
        migrations.AddField(
            model_name='job',
            name='Longitude_Destination',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Longitude_Pickup',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
