# Generated by Django 4.1.2 on 2022-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_job_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Distance',
            field=models.FloatField(default=1, max_length=300),
        ),
    ]
