# Generated by Django 4.1.2 on 2022-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_job_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Tip',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
