# Generated by Django 4.1.2 on 2022-11-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_job_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_comment_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_follow_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_like_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_repost_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationJob', to='main.job'),
        ),
    ]
