# Generated by Django 4.1.2 on 2022-11-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
