# Generated by Django 4.1.2 on 2022-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_job_author_profile_messages_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='License_Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
