# Generated by Django 4.1.2 on 2022-11-27 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
