# Generated by Django 4.1.2 on 2022-11-30 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Group',
        ),
        migrations.AddField(
            model_name='post',
            name='Caption',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='CommentCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='ImageString',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='InteractionID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='IsComment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='IsLike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='IsOriginalpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='IsQuotepost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='LikeCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='PostComments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='main.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='PostItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='main.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='ReplyingTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='RepostAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repostAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='Reposted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ReshareCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='UserHasLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User_Groups',
        ),
    ]
