# Generated by Django 4.1.2 on 2022-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_images_name_remove_post_group_post_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
