# Generated by Django 4.1.2 on 2023-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
