# Generated by Django 4.1.2 on 2023-01-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_job_driver_pay_job_height_job_length_job_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='CompletionImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='Phone_Number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
