# Generated by Django 4.1.2 on 2023-01-18 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_job_completionimage_job_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Phone_Number',
            field=models.CharField(default=uuid.uuid1, max_length=11),
        ),
    ]
