# Generated by Django 4.1.2 on 2023-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_job_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
