# Generated by Django 4.1.2 on 2023-01-25 16:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_job_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Time_Needed',
            field=models.DateTimeField(default=main.models.default_start_time),
        ),
    ]
