# Generated by Django 4.1.2 on 2023-02-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_job_time_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
