# Generated by Django 4.1.2 on 2023-02-09 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_message_image_alter_message_msg_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ImageString',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
    ]
