# Generated by Django 4.1.2 on 2023-02-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_message_imagestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Messages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Notifications',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
