# Generated by Django 4.1.2 on 2023-02-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_message_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='post',
            new_name='job',
        ),
    ]
