# Generated by Django 4.1.2 on 2023-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_post_message_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=18, null=True),
        ),
    ]
