# Generated by Django 4.1.2 on 2023-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Latitude_Destination',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Latitude_Pickup',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Longitude_Destination',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Longitude_Pickup',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
