# Generated by Django 4.1.2 on 2023-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_profile_latitude_destination_profile_latitude_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isCompleteNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='isInPickedUpNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='isInProgressNotification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='isMessageNotification',
            field=models.BooleanField(default=False),
        ),
    ]
