# Generated by Django 4.1.2 on 2023-02-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_notification_iscompletenotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isInPickedUpNotification',
            new_name='isPickedUpNotification',
        ),
    ]
