# Generated by Django 4.1.2 on 2023-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_rename_isinpickedupnotification_notification_ispickedupnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msg',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
