# Generated by Django 4.1.2 on 2023-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_notification_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Stripe_Link',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
