# Generated by Django 4.1.2 on 2023-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_profile_stripe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Stripe_Link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
