# Generated by Django 4.1.2 on 2023-02-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_profile_stripe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Stripe_Account_ID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Stripe_Customer_ID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
