# Generated by Django 4.1.2 on 2023-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_profile_stripe_account_id_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
