# Generated by Django 4.1.2 on 2023-07-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Banking_Account_Number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Banking_Routing_Number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='License_Plate_Number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
